version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 14
    pre_build:
        commands:
            - npm install
    build: 
        commands:
            -NODE_ENV=production npm run build
    post_build:
        commands:
            - rm -rf node_modules

artifacts:
    files:
        - "**/*"
    discard-paths: yes
    base-directory: build