version: 0.1

phases:
    install:
      runtime-versions:
        nodejs: 14.x
    pre_build:
        commands:
            - npm install
    build: 
        commands:
            - npm run build
artifacts:
    type: zip
    files:
        - package.json
        - package-lock.json
        - "build/**/*"
    discard-paths: no
    base-directory: build

    